server:
  port: 8080

spring:
  application:
    name: ratrip
  profiles:
    include: API-KEY
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_SCHEMA}?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 2000
        loggerLevel: FULL

logging:
  level:
    ddd.caffeine.ratrip: DEBUG

