server:
  port: 8080

spring:
  application:
    name: ratrip
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_SCHEMA}?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 15000
        loggerLevel: FULL

logging:
  level:
    ddd.caffeine.ratrip: DEBUG

