secret:
  key:
    jwt: ${JWT_SECRET_KEY}

    kakao:
      rest-api-key: ${KAKAO_API_KEY}
      redirect-uri: ${KAKAO_REDIRECT_URI}

    naver:
      naver_client: ${NAVER_ID}
      naver_secret: ${NAVER_SECRET}


