secret:
  jwt-secret: ${JWT_SECRET_KEY}

  kakao:
    rest-api-key: ${KAKAO_API_KEY}
    redirect-uri: ${KAKAO_REDIRECT_URI}

  naver:
    client-key: ${NAVER_CLIENT_KEY}
    secret-key: ${NAVER_SECRET_KEY}


